apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: goserver
  newName: gutherry/projeto
  newTag: c56968f23bbb74915370ee0018f9ecf04fa541c8
