name: CDGitops

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      # Adicione aqui seus testes
      - name: Run tests
        run: |
          echo "Executando testes..."
          # Exemplo: go test ./... -v

  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ secrets.DOCKER_USERNAME }}/projeto
        tags: |
          type=sha,format=long
          type=raw,value=latest
          type=semver,pattern={{version}}

    - name: Build and push image to Dockerhub
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/projeto:latest
        cache-to: type=inline
        platforms: linux/amd64,linux/arm64

    - name: Setup Kustomize
      uses: imranismail/setup-kustomize@v1
      with: 
        kustomize-version: "5.1.1"

    - name: Checkout GitOps repository
      uses: actions/checkout@v4
      with:
        repository: gutherry/gitops
        token: ${{ secrets.GITOPS_PAT }}
        path: gitops

    - name: Update Kubernetes resources
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      run: |
        cd gitops/k8s
        kustomize edit set image goserver=$DOCKER_USERNAME/projeto:$GITHUB_SHA
        
    - name: Commit and push changes
      env:
        GITOPS_PAT: ${{ secrets.GITOPS_PAT }}
      run: |
        cd gitops
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update application to $GITHUB_SHA"
        git push https://x-access-token:${GITOPS_PAT}@github.com/gutherry/gitops.git HEAD:main